name: Village Android E2E
on:
  pull_request:
    branches: ["*"]
jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: e2e-test
  maestro_test:
    needs: [build_android]
    type: maestro
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path: [".maestro/demo-onboarding.yaml", ".maestro/help-request.yaml", ".maestro/handoff.yaml"]
